routes/web.php
<?php

use Illuminate\Routing\Router ;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\App;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;
use App\Http\Controllers\Shop\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'middleware' => ['trueFallbackLocale'],
], function() {
    Route::get('/', function () {
        return view('dashboard');
    });
});

$dashboardView = function () {
    return view('admin.dashboard');
};

Route::prefix('admin')
    ->group(function() use ($dashboardView) {
        Route::get('/login', $dashboardView)->name('login');
        Route::get('/password-reset', $dashboardView)->name('password.reset');
    });

Route::get('/{slug?}', [DashboardController::class, 'index'])
    ->where('slug', '.*')
    ->name('shop');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Arr;
use Illuminate\Support\Collection;
use Storage;
use Image as InerventionImage;
use Symfony\Component\HttpFoundation\File\File;
use DB;
use App\Http\Controllers\Shop\ProductsController;

class Product extends Model
{
    use HasFactory, Traits\Translatable, Traits\Search;

    public $translatable = ['name', 'slug', 'description'];

    protected $translationClass = ProductTranslation::class;
    protected $translationKey = 'product_id';  

    protected $fillable = [
        'category_id',
        'sku',
        'price',
        'quantity',
        'is_active',
        'product_id',
        'products_binding_id',
    ];

    protected $casts = [
        'is_active' => 'boolean'
    ];

    protected $appends = [
        'rid'
    ];

    protected $searchColumns = [
        'slug', 'name', 'description',
    ];

    public function attributes()
    {
        return $this->belongsToMany(
            Attribute::class, 
            'product_attribute_values',
            'product_id',
            'attribute_id'
        )->using(ProductAttributeValue::class);
    }

    public function binding()
    {
        return $this->belongsTo(ProductBinding::class, 'products_binding_id');
    }

    public function attributesValues() 
    {
        return $this->hasMany(ProductAttributeValue::class, 'product_id');
    }

    public function image() 
    {
        return $this->hasOne(Image::class, 'product_id');
    }

    public function images() 
    {
        return $this->hasMany(Image::class, 'product_id');
    }

    public function variants() 
    {
        return $this->hasMany(Product::class, 'product_id')->latest();
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function saveAttributes(array $attributeDtos)
    {
        $attributeDtos = collect($attributeDtos);
        $ids = $attributeDtos->map(function($attributeDto) {
            return $attributeDto->getAttributeId();
        })->filter();

        $this->attributesValues()->whereNotIn('attribute_id', $ids->toArray())->delete();

        $attributeDtos->each(function($attributeDto) {
            $this->attributesValues()->updateOrCreate([
                'attribute_id' => $attributeDto->getAttributeId(),
            ], $attributeDto->toArray());
        });
    }

    public function saveVariants(array $variantDtos)
    {
        $variantDtos = collect($variantDtos);
        $ids = $variantDtos->map(function($dto) {
            return $dto->getId();
        })->filter();

        $variantsToRemove = $this->variants()->whereNotIn('id', $ids->toArray())->get();
        $variantsToRemove->each(function($variant) {
            $variant->delete();
        });

        $variantDtos->each(function($dto) {
            if ($dto->isNew()) {
                $product = $this->variants()->create($dto->toArray());
            } else {
                $product = $this->variants()->find($dto->getId());
                $product->update($dto->toArray());
            }

            $product->saveAttributes($dto->getAttributes());
        });
    }

    public function saveImages(array $images)
    {
        $imageModels = [];
        $imagesDisk = Storage::disk('images');
        $thumbnailsDisk = Storage::disk('thumbnails');

        foreach ($images as $image) {

            if(!$image instanceof File) {
              throw new \Exception("image must be instance of ".File::class);              
            }

            $name = $image->getFilename();
            $name = time().'_'.$name;

            $imagesDisk->put($name, $image->getContent());

            $thumbnail = InerventionImage::make($image->getRealPath());
            $thumbnail->resize(300, 300, function ($constraint) {
                $constraint->aspectRatio();
            })->encode($image->getExtension());

            $thumbnailsDisk->put($name, $thumbnail);
            $imageModels[] = new Image([
                'filename' => $name
            ]);
        }
        
        $this->images()->saveMany($imageModels);
    }

    public function deleteImages(array $ids)
    {
        $images = $this->images()->find($ids);
        $images->each(function($image) {
            $image->delete();
        });
    }

    public function getRidAttribute()
    {
        return 'rid'.uniqid();
    }

    public function scopeNoVariantsFilter($query)
    {
        return $query->whereNull('products.product_id');
    }

    public function getRelatedProductsAttribute() : array
    {
        $products = optional($this->binding)->products; 

        if (!$products) {
            return [];
        }

        return $products->pluck('id')->toArray();
    }

    public function saveRelatedProducts(array $relatedProducts)
    {
        if (count($relatedProducts) == 0) {
            $this->update([
                'products_binding_id' => null,
            ]);
        } else {
            $relatedProducts[] = $this->id;

            $binding = ProductBinding::create();
            $binding->bindProducts($relatedProducts);
        }

        $bindindsToDestroy = ProductBinding::doesntHave('products')->delete();
    }

    public function view()
    {
        return view('shop.product', [
            'model' => $this
        ]);
    }
    
    public function controller()
    {
        return ProductsController::class; 
    }

    public function action()
    {
        return 'show';
    }

    public function getPriceFormatAttribute()
    {
        return number_format(
            $this->price,
            2,
            ',',
            ' '
        ).' PLN' ;
    }

    public function getAdditionalAttributesDescAttribute() : array
    {
        $customAttributes = [];

        foreach ($this->attributesValues as $value) {
            $attribute = $value->attribute;
            $customAttributes[$attribute->name] = $attribute->class_type->getDescValue($value);
        }

        return $customAttributes;
    }

    public function getAdditionalAttributesAttribute() : array
    {
        $customAttributes = [];

        foreach ($this->attributesValues as $value) {
            $attribute = $value->attribute;
            $customAttributes[$attribute->name] = $attribute->class_type->getValue($value);
        }

        return $customAttributes;
    }

    public function getCustomAttributesAttribute()
    {
        $attributes = [];
        
        foreach ($this->attributesValues as $value) {
            $attribute = $value->attribute;
            $attributes[$attribute->name] = $attribute->class_type->getDescValue($value);
        }

        return $attributes;
    }

    public function getCustomAttribute($attribute)
    {
        return Arr::get($this->custom_attributes, $attribute);
    }

    public function getAttributeVariants($attribute)
    {
        $variants = $this->variants;

        $attributeVariants = $variants->map(fn($variant) => $variant->getCustomAttribute($attribute));
        $attributeVariants->push($this->getCustomAttribute($attribute));

        return $attributeVariants
            ->filter()
            ->unique()
            ->values();
    }

    public function getUrlAttribute()
    {
        if (!$slug = $this->slug) {
            return null;
        }

        return content_locale_url($slug, $this->locale);
    }  

    public function getViewAttribute()
    {
        return 'product';
    }
}

app/Http/Controllers/Shop/CategoriesController.php
<?php

namespace App\Http\Controllers\Shop;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public function index(Request $request)
    {
        $model = $request->route('slug');
        
        return view('shop.categories', [
            'model' => $model
        ]); 
    }
}

app/Http/Controllers/Shop/DashboardController.php
<?php

namespace App\Http\Controllers\Shop;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Routing\ControllerDispatcher;

class DashboardController extends Controller
{
    public function index(Request $request)
    {
        $model = $request->route('slug');

        if ($model) {
            $route = app(\Illuminate\Routing\Route::class);
            $container = app();

            return (new ControllerDispatcher($container))
                ->dispatch($route, resolve($model->controller()), $model->action());
        }

        return view('admin.dashboard');
    }
}

app/Http/Controllers/Shop/ProductsController.php
<?php

namespace App\Http\Controllers\Shop;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB;

class ProductsController extends Controller
{
    public function index(Request $request)
    {       
        // dd($request->all());
        // $priceFrom = $request->input('price.from');
        // $priceTo = $request->input('price.to');
        // dd($priceFrom, $priceTo, $request->all());

        $category = $request->route('slug');
        $model->translateLoad(['ancestors']);

        $breadcrumb = $category->ancestors
            ->map(fn($ancestor) => ([
                'text' => $ancestor->name,
                'href' => $ancestor->url,
            ]));
        $breadcrumb->push([
            'text' => $category->name,
            'href' => $category->url,
        ]);
        $breadcrumb->prepend([
            'text' => 'Start',
            'href' => url('/'),
        ]);

        $products = $category->products()->translate()
            ->translateWith([
                'image',
                'binding.products.image',
                'attributesValues.option',
                'attributesValues.attribute',
                'variants.attributesValues.attribute',
                'variants.attributesValues.option',
                'binding.products.attributesValues.attribute',
                'binding.products.variants.attributesValues.attribute',
                'binding.products.variants.attributesValues.option',
                'binding.products.attributesValues.option',
            ])
            ->groupBy(DB::raw('ifnull(products_binding_id,id)'))
            ->paginate(100);

        $attributes = $category->group->attributes()
            ->translate()
            ->translateWith([
                'options'
            ])
            ->get();

        return view('shop.products', [
            'products' => $products,
            'attributes' => $attributes,
            'breadcrumb' => $breadcrumb,
            'category' => $category,
        ]);
    }

    public function show(Request $request)
    {
        $category = $request->route('slug');

        return view('shop.product', [
            'model' => $category
        ]);
    }
}

resources/views/shop/categories.blade.php
@extends('shop.master')

@section('category')
@json($model->load('ancestors')->toArray())
@endsection

@section('breadcrumb')
@php
$items = $model->ancestors->map(fn($ancestor) => ([
	'text' => $ancestor->name,
	'href' => $ancestor->url,
]));
$items->push([
	'text' => $model->name,
	'href' => $model->url,
]);
$items->prepend([
	'text' => 'Start',
	'href' => url('/'),
]);
@endphp
<b-breadcrumb :items='@json($items->toArray())'></b-breadcrumb>
@endsection

@section('content')
<h1>{{$model->name}}</h1>
<b-card-group columns>
	@foreach ($model->children as $child)
		<b-card
    		title="{{$child->name}}">			
		</b-card>
	@endforeach
</b-card-group>
@endsection

resources/views/shop/category.blade.php
@extends('shop.master')

@section('category')
@json($model->load('ancestors')->toArray())
@endsection

@section('breadcrumb')
@php
$items = $model->ancestors->map(fn($ancestor) => ([
	'text' => $ancestor->name,
	'href' => $ancestor->url,
]));
$items->push([
	'text' => $model->name,
	'href' => $model->url,
]);
$items->prepend([
	'text' => 'Start',
	'href' => url('/'),
]);
@endphp
<b-breadcrumb :items='@json($items->toArray())'></b-breadcrumb>
@endsection

@section('content')
<h1>{{$model->name}}</h1>
@endsection

resources/views/shop/master.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{config('app.name')}}</title>
    <meta 
      name="description" 
      content="Panel admina">
    <link rel="canonical" href="{{url('/')}}">
    <link 
      rel="stylesheet" 
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" />
    <link href="{{ mix('css/shop/app.css')}}" rel="stylesheet" type="text/css"> 
  </head>
  <body>
    <div 
      id="startLoader">
      <div class="spinner-grow" role="status" style="width: 5rem; height: 5rem;">
        <span class="sr-only">Loading...</span>
      </div>
    </div>
    <div id="app">
      <app>
        <layout>
          <template #menu-items>
            <menu-items 
              :menu-items='@json($menuItemsTree)'>
            </menu-items>
          </template>
          @section('sidebar')
            <template #sidebar>
              <sidebar
                :categories='@json($categoriesTree)'
                :current-category='@yield('category')'>
              </sidebar>
            </template>
          @show
          @yield('breadcrumb')
          @yield('content')
        </layout>
      </app>
    </div>
    <input type="hidden" id="appName" value="{{config('app.name')}}"/>
    <script src="{{ mix('js/shop/app.js') }}"></script>   
  </body>
</html>

resources/views/shop/product.blade.php
@extends('shop.master')

@section('breadcrumb')
@php
$category = $model->category()->translate()->first();
$items = $category->ancestors()
	->translate()
	->get()
	->map(fn($ancestor) => ([
		'text' => $ancestor->name,
		'href' => $ancestor->url,
	]));
$items->push([
	'text' => $category->name,
	'href' => $category->url,
]);
$items->push([
	'text' => $model->name,
	'href' => $model->url,
]);
$items->prepend([
	'text' => 'Start',
	'href' => url('/'),
]);
@endphp
<b-breadcrumb :items='@json($items->toArray())'></b-breadcrumb>
@endsection

@section('sidebar', '')

@section('content')
<b-row>
	<b-col md="3">
		<b-img thumbnail src="{{$model->image->image_url}}" alt="Image 1"></b-img></b-col>
	<b-col>
		<h1 class="mb-3">{{$model->name}}</h1>
	</b-col>
</b-row>
@php
DB::connection()->enableQueryLog();

// dd($products->getCollection()->get(3)->toArray());
@endphp

@php
Log::info(DB::getQueryLog());
@endphp
@endsection

resources/views/shop/products.blade.php
@extends('shop.master')

@section('category')
@json($category->toArray())
@endsection

@section('breadcrumb')
<b-breadcrumb :items='@json($breadcrumb->toArray())'></b-breadcrumb>
@endsection

@section('content')
<h1 class="mb-3">{{$category->name}}</h1>
@php
DB::connection()->enableQueryLog();
@endphp
<attributes-form
	url="{{request()->url()}}"
	:query='@json(request()->input('phrase'))'>
	<template #default="{model, clearFiltersKey}">
		<b-row>
			<b-col class="col">
				<component 
					is="number-field"
					name="price"
					:label="lang.get('messages.price')"
					:query='@json(request()->input('price'))'
					:model="model"
					ref="price"></component>
			</b-col>
			<b-col class="col" lg="2">
				<component 
					is="radio-field"
					name="order"
					:label="lang.get('messages.order')"
					:options="['cheapest', 'most_expensive', 'newest'].map((item) => ({
						name: lang.get('messages.'+item),
						value: item
					}))"
					:query='@json(request()->input('order'))'
					:model="model"
					ref="order"></component>
			</b-col>
			@foreach ($attributes as $index => $attribute)
				@if ($attribute->class_type->getShopComponent())
					<b-col class="col" lg="2">
						<component 
							is="{{$attribute->class_type->getShopComponent()}}"
							:dropright='@json((($index + 2) % 5) == 0 ? true : false)'
							name="{{$attribute->name}}"
							label="{{$attribute->label}}"
							:options='@json($attribute->options)'
							:query='@json(request()->input($attribute->name))'
							:model="model"
							ref="{{$attribute->name}}"></component>
					</b-col>
				@endif
			@endforeach
		</b-row>		
	</template>
</attributes-form>
<div class="grid-p-sm">
	<b-row>
		@foreach ($products as $product)
			<b-col lg="4" class="col">
				<product-card
					:img-src='@json(optional($product->image)->thumbnail_url)'
		    		title="{{$product->name}}"
		    		sub-title="{{$product->getAttributeVariants('size')->implode(' | ')}}"
		    		price="{{ $product->price_format}}"
		    		:url='@json($product->url)'
		    		key="{{$product->id}}">
		    		@if($product->binding)
		    		<template #thumbs>  
			    		<b-row>  			
				    		@foreach ($product->binding->products->take(4) as $bindProduct)
				    			<binding-product-thumb 
									:src='@json(optional($bindProduct->image)->thumbnail_url)'
									:url='@json($bindProduct->url)'
									title="{{$bindProduct->name}}"
									sub-title="{{$bindProduct->getAttributeVariants('size')->implode(' | ')}}"
		    						key="{{$bindProduct->id}}"
		    						price="{{ $bindProduct->price_format}}"
									>
								</binding-product-thumb>
				    		@endforeach
				    	</b-row>
		    		</template>
		    		@endif
		    	</product-card>
		    </b-col>
		@endforeach   
	</b-row>
</div>
@php
Log::info(DB::getQueryLog());
@endphp
<div class="d-flex justify-content-center">  
	{{ $products->links('pagination::bootstrap-4') }}
</div>
@endsection